apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: corinnekrych
    provider: github
    repository: tooo
  name: corinnekrych-tooo
spec:
  description: Imported application for corinnekrych/tooo
  httpCloneURL: https://github.com/corinnekrych/tooo.git
  org: corinnekrych
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: tooo
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/corinnekrych/tooo.git
